export default {
	login: "mayursamnani36",
	id: 54547503,
	node_id: "MDQ6VXNlcjU0NTQ3NTAz",
	avatar_url: "https://avatars.githubusercontent.com/u/54547503?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/mayursamnani36",
	html_url: "https://github.com/mayursamnani36",
	followers_url: "https://api.github.com/users/mayursamnani36/followers",
	following_url:
		"https://api.github.com/users/mayursamnani36/following{/other_user}",
	gists_url: "https://api.github.com/users/mayursamnani36/gists{/gist_id}",
	starred_url:
		"https://api.github.com/users/mayursamnani36/starred{/owner}{/repo}",
	subscriptions_url:
		"https://api.github.com/users/mayursamnani36/subscriptions",
	organizations_url: "https://api.github.com/users/mayursamnani36/orgs",
	repos_url: "https://api.github.com/users/mayursamnani36/repos",
	events_url: "https://api.github.com/users/mayursamnani36/events{/privacy}",
	received_events_url:
		"https://api.github.com/users/mayursamnani36/received_events",
	type: "User",
	site_admin: false,
	name: null,
	company: null,
	blog: "https://mayursamnani36.github.io/",
	location: null,
	email: null,
	hireable: true,
	bio: "3rd yearite at IIT Guwahati || Interested in web development || ",
	twitter_username: null,
	public_repos: 7,
	public_gists: 0,
	followers: 0,
	following: 8,
	created_at: "2019-08-26T16:23:32Z",
	updated_at: "2021-06-24T15:11:25Z",
};
